### ISSUE TITLE
Angle Planes does not appear when installed in Slicer 4.11

### ISSUE THREAD

**Issue by luciacev** [DCBIA-OrthoLab/AnglePlanes-Extension#16]
@jcfr 
@bpaniagua 
@JEHoctor
@aruellas

When we install the AnglePlanes extension in Slicer 4.11 even after we re-start Slicer we cannot. see the extension in the list of modules and if we search we cannot find Angle Planes. Thanks!

**Comment by jcfr** [comment]
Closing.

This should has been fixed by https://github.com/DCBIA-OrthoLab/AnglePlanes-Extension/pull/17, https://github.com/DCBIA-OrthoLab/SlicerCMF/pull/11 and https://github.com/Slicer/ExtensionsIndex/pull/1700

@luciacev  @aruellas  Would be great if you could try the new plane markup annotation and evaluate if it would work for you. Consider adding comments to https://github.com/DCBIA-OrthoLab/AnglePlanes-Extension/issues/19
